const K='fitnessProV3',PK='fitnessPlanV3';
const DEFAULT={weeks:Array.from({length:16},(_,i)=>({week:i+1,focus:i<4?'Возвращение в форму':i<8?'Развитие выносливости':i<12?'Прогресс нагрузки':'Закрепление формы',days:[
{dow:1,type:'RUN',title:'Лёгкий бег + корпус',run:i<4?'25–30 мин':i<8?'30–35 мин':i<12?'35–40 мин':'40–45 мин',items:[['Планка','3×45 сек'],['Скручивания','3×15']]},
{dow:2,type:'REST',title:'Отдых',items:[]},
{dow:3,type:'STRENGTH',title:'Руки + верх тела',run:'10 мин разминки',items:[['Бицепс со штангой','3×10'],['Молотки','3×10'],['Разгибание на блоке','3×12'],['Жим в тренажёре','3×10']]},
{dow:4,type:'REST',title:'Отдых / прогулка',items:[]},
{dow:5,type:'RUN',title:'Бег · выносливость',run:i<4?'30 мин':i<8?'35 мин':i<12?'40 мин':'45 мин',items:[['Планка','3×45 сек'],['Dead bug','3×10']]},
{dow:6,type:'STRENGTH',title:'Ноги + спина + руки',run:'10 мин разминки',items:[['Тяга верхнего блока','3×10'],['Жим ногами','3×10'],['Бицепс','3×10'],['Пресс','3×15']]},
{dow:0,type:'REST',title:'Восстановление',items:[]}
]}))};
let state=JSON.parse(localStorage.getItem(K)||'null')||{days:{},sets:{},weights:[],profile:{age:28,height:176,weight:79},dark:false};
let plan=JSON.parse(localStorage.getItem(PK)||'null')||DEFAULT,current='today',offset=0,weekSel=1;
const $=x=>document.getElementById(x),todayKey=()=>new Date().toISOString().slice(0,10);
function save(){localStorage.setItem(K,JSON.stringify(state));localStorage.setItem(PK,JSON.stringify(plan))}
function dateKey(d){return d.toISOString().slice(0,10)}
function week(d=new Date()){let s=new Date('2026-08-10T12:00:00');return Math.min(16,Math.max(1,Math.floor((d-s)/604800000)+1))}
function dp(d){return plan.weeks[week(d)-1].days.find(x=>x.dow===d.getDay())}
function ds(d){let k=dateKey(d);return state.days[k]||(state.days[k]={checks:{},status:'PLANNED'})}
function pct(d){let p=dp(d),s=ds(d);if(p.type==='REST')return 100;return p.items.length?Math.round(Object.values(s.checks).filter(Boolean).length/p.items.length*100):0}
function toast(x){$('toast').textContent=x;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1700)}
function nav(n){current=n;document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.screen===n));({today,calendar,planView,progress,profile}[n])()}
function hdr(t){$('pageTitle').textContent=t;$('weekLabel').textContent=`НЕДЕЛЯ ${week()} / 16`}
function ru(d){return d.toLocaleDateString('ru-RU',{weekday:'long',day:'numeric',month:'long'})}
function today(){hdr('Сегодня');let d=new Date(),p=dp(d),s=ds(d),q=pct(d);if(p.type==='REST'){$('screen').innerHTML=`<div class="card hero"><div class="eyebrow">${ru(d)}</div><h2>Восстановление</h2><p class="muted">Сегодня отдых. Прогулка, сон и восстановление.</p></div><div class="card"><h2>Следующая тренировка</h2><p class="muted">${next()}</p><button class="btn full" onclick="nav('calendar')">Открыть календарь</button></div>`;return}
$('screen').innerHTML=`<div class="card hero"><div class="eyebrow">${ru(d)}</div><h2>${p.title}</h2><p class="muted">${p.run||'Силовая по плану'}</p><div class="row"><b>${q}%</b><span>${q===100?'Выполнено':'В процессе'}</span></div><div class="progress"><i style="width:${q}%"></i></div></div>
<div class="card"><div class="row"><h2>🏃 Бег</h2><button class="btn secondary" onclick="run()">Внести факт</button></div><div class="grid2"><div class="metric"><small class="muted">Цель</small><b>${p.run||'—'}</b></div><div class="metric"><small class="muted">Факт</small><b>${s.run?s.run+' мин':'—'}</b></div></div></div>
<div class="card"><h2>☑️ Чек-лист</h2>${p.items.map((x,i)=>`<label class="check"><input type="checkbox" ${s.checks[i]?'checked':''} onchange="toggle(${i},this.checked)"><span><b>${x[0]}</b><br><span class="muted">${x[1]}</span></span></label>`).join('')}</div>
<div class="card"><h2>🏋️ Подходы</h2>${p.items.map((x,i)=>exercise(d,i,x)).join('')}</div>
<div class="card"><h2>Оценка</h2><div class="formgrid"><div class="field"><label>Энергия 1–10</label><input id="energy" type="number" min="1" max="10" value="${s.energy||7}"></div><div class="field"><label>RPE 1–10</label><input id="rpe" type="number" min="1" max="10" value="${s.rpe||6}"></div></div><div class="field" style="margin-top:10px"><label>Заметка</label><textarea id="note">${s.note||''}</textarea></div><button class="btn full" onclick="finish()">Сохранить тренировку</button></div>`}
function exercise(d,i,x){let k=dateKey(d)+'_'+i,a=state.sets[k]||[{w:'',r:'',done:false},{w:'',r:'',done:false},{w:'',r:'',done:false}];return `<div class="exercise"><div class="row"><b>${x[0]}</b><span class="badge">${x[1]}</span></div><div class="sets"><small>#</small><small>Вес</small><small>Повт.</small><small></small>${a.map((s,j)=>`<span>${j+1}</span><input type="number" step=".5" value="${s.w}" placeholder="кг" onchange="sv('${k}',${j},'w',this.value)"><input type="number" value="${s.r}" placeholder="повт." onchange="sv('${k}',${j},'r',this.value)"><input type="checkbox" ${s.done?'checked':''} onchange="sv('${k}',${j},'done',this.checked)">`).join('')}</div></div>`}
function toggle(i,v){ds(new Date()).checks[i]=v;save();today()}
function sv(k,j,f,v){state.sets[k]??=[{w:'',r:'',done:false},{w:'',r:'',done:false},{w:'',r:'',done:false}];state.sets[k][j][f]=f==='done'?v:v;save()}
function finish(){let s=ds(new Date());s.completion=pct(new Date());s.status=s.completion>=100?'COMPLETED':'PARTIALLY_COMPLETED';s.energy=+$('energy').value;s.rpe=+$('rpe').value;s.note=$('note').value;save();toast('Тренировка сохранена');today()}
function run(){let x=prompt('Фактическое время бега, минут:',ds(new Date()).run||30);if(x!==null){ds(new Date()).run=+x||0;save();toast('Бег сохранён');today()}}
function next(){for(let i=1;i<8;i++){let d=new Date();d.setDate(d.getDate()+i);if(dp(d).type!=='REST')return ru(d)+' · '+dp(d).title}return'скоро'}
function calendar(){hdr('Календарь');let b=new Date();b.setDate(1);b.setMonth(b.getMonth()+offset);let y=b.getFullYear(),m=b.getMonth(),n=new Date(y,m+1,0).getDate(),o=(b.getDay()+6)%7,h=`<div class="card"><div class="row"><button class="btn secondary" onclick="move(-1)">‹</button><h2>${b.toLocaleDateString('ru-RU',{month:'long',year:'numeric'})}</h2><button class="btn secondary" onclick="move(1)">›</button></div><div class="calendar">${['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].map(x=>`<div class="calhead">${x}</div>`).join('')}`;for(let i=0;i<o;i++)h+='<div></div>';for(let x=1;x<=n;x++){let d=new Date(y,m,x),s=state.days[dateKey(d)],c=`day ${dp(d).type!=='REST'?'training':''} ${s?.status==='COMPLETED'?'done':''} ${s?.status==='PARTIALLY_COMPLETED'?'partial':''} ${dateKey(d)===todayKey()?'today':''}`;h+=`<button class="${c}" onclick="openD('${dateKey(d)}')">${x}</button>`}h+='</div></div><div class="card muted">Синий = тренировка · ✓ = выполнено · • = частично</div>';$('screen').innerHTML=h}
function move(x){offset+=x;calendar()}
function openD(k){let d=new Date(k+'T12:00:00'),p=dp(d),s=state.days[k];alert(`${ru(d)}\n\n${p.title}\n${p.run||'Отдых'}\n\nСтатус: ${s?.status==='COMPLETED'?'Выполнено':s?.status==='PARTIALLY_COMPLETED'?'Частично':'Запланировано'}`)}
function planView(){hdr('План');let w=plan.weeks[weekSel-1];$('screen').innerHTML=`<div class="weekbar">${plan.weeks.map(x=>`<button class="${x.week===weekSel?'active':''}" onclick="weekSelect(${x.week})">Нед. ${x.week}</button>`).join('')}</div><div class="card hero"><div class="eyebrow">16 НЕДЕЛЬ</div><h2>Неделя ${w.week}</h2><p class="muted">${w.focus}</p></div>`+w.days.map(x=>`<div class="card listrow"><div class="row"><div><b>${['Вс','Пн','Вт','Ср','Чт','Пт','Сб'][x.dow]}</b><h3>${x.title}</h3><span class="muted">${x.run||'Восстановление'}</span></div><span class="badge ${x.type==='REST'?'ok':''}">${x.type==='REST'?'ОТДЫХ':'ТРЕНИРОВКА'}</span></div>${x.items.length?'<p class="muted">'+x.items.map(a=>a[0]+' '+a[1]).join(' · ')+'</p>':''}</div>`).join('')}
function weekSelect(x){weekSel=x;planView()}
function progress(){hdr('Прогресс');let a=Object.values(state.days),done=a.filter(x=>x.status==='COMPLETED').length,part=a.filter(x=>x.status==='PARTIALLY_COMPLETED').length,rs=a.filter(x=>x.rpe).map(x=>x.rpe),r=rs.length?(rs.reduce((x,y)=>x+y,0)/rs.length).toFixed(1):'—';$('screen').innerHTML=`<div class="grid2"><div class="metric"><small class="muted">Выполнено</small><b>${done}</b></div><div class="metric"><small class="muted">Частично</small><b>${part}</b></div><div class="metric"><small class="muted">Средний RPE</small><b>${r}</b></div><div class="metric"><small class="muted">Вес</small><b>${state.weights?.at(-1)||state.profile.weight} кг</b></div></div><div class="card"><h2>Выполнение</h2><div class="big">${a.length?Math.round(done/a.length*100):0}%</div><div class="progress"><i style="width:${a.length?done/a.length*100:0}%"></i></div></div><div class="card"><h2>Добавить вес</h2><div class="row"><input id="weight" type="number" step=".1" placeholder="78.5"><button class="btn" onclick="weightAdd()">Сохранить</button></div><p class="muted">${state.weights?.length?state.weights.join(' → ')+' кг':'Нет измерений'}</p></div>`}
function weightAdd(){let x=+$('weight').value;if(x){state.weights??=[];state.weights.push(x);state.profile.weight=x;save();toast('Вес сохранён');progress()}}
function profile(){hdr('Профиль');$('screen').innerHTML=`<div class="card"><h2>Параметры</h2><div class="formgrid"><div class="field"><label>Возраст</label><input id="age" type="number" value="${state.profile.age}"></div><div class="field"><label>Рост, см</label><input id="height" type="number" value="${state.profile.height}"></div><div class="field"><label>Вес, кг</label><input id="pweight" type="number" step=".1" value="${state.profile.weight}"></div><div class="field"><label>Тренировок/нед.</label><select id="freq"><option>2</option><option selected>3</option><option>4</option></select></div></div><button class="btn full" onclick="profileSave()">Сохранить</button></div><div class="card"><h2>Резервная копия</h2><button class="btn" onclick="exportData()">Экспорт JSON</button><button class="btn secondary" onclick="importData()" style="margin-left:6px">Импорт JSON</button></div><div class="card"><h2>Приложение</h2><p class="muted">PWA · offline · локальное хранение · без аккаунта и сервера.</p><button class="btn danger" onclick="reset()">Удалить историю</button></div>`}
function profileSave(){state.profile.age=+$('age').value;state.profile.height=+$('height').value;state.profile.weight=+$('pweight').value;save();toast('Профиль сохранён')}
function exportData(){let b=new Blob([JSON.stringify({state,plan,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='fitness-planner-backup.json';a.click()}
function importData(){let i=document.createElement('input');i.type='file';i.accept='.json';i.onchange=()=>{let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(x.state)state=x.state;if(x.plan)plan=x.plan;save();toast('Импорт завершён');profile()}catch(e){alert('Неверный файл')}};r.readAsText(i.files[0])};i.click()}
function reset(){if(confirm('Удалить историю тренировок, подходов, бега и веса?')){state={days:{},sets:{},weights:[],profile:state.profile,dark:state.dark};save();toast('История очищена');profile()}}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>nav(b.dataset.screen));
$('themeBtn').onclick=()=>{state.dark=!state.dark;document.body.classList.toggle('dark',state.dark);save()}
if(state.dark)document.body.classList.add('dark');nav('today');if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});